version: 2

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Install GIT
          command: 'apt-get update && apt-get install -y git'
      - run:
          name: Install Google Tests
          command: 'cd cpp/tests && git clone https://github.com/google/googletest.git'
      - run: 
          name: Create Build, Binary Files
          command: 'cd cpp/tests && cmake -H. -Bbuild && cmake --build build'
      - run:
          name: SVR Unit Testing
          command: 'cd cpp/tests/bin && ./test_SVR'
